version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name:  ##SUBDOMAIN##-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '##DB_ROOT_PASSWORD##'
      MYSQL_DATABASE: ##DB_NAME##
      MYSQL_USER: ##DB_USER##
      MYSQL_PASSWORD: ##DB_PASSWORD##
    volumes:
      - ./db/data:/var/lib/mysql
  web:
    image: tuxgasy/dolibarr
    container_name: ##SUBDOMAIN##-dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: ##DB_USER##
      DOLI_DB_PASSWORD: '##DB_PASSWORD##'
      DOLI_DB_NAME: ##DB_NAME##
      DOLI_URL_ROOT: 'http://0.0.0.0'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
      VIRTUAL_HOST: '##SUBDOMAIN##-crm.archops.fr'
      LETSENCRYPT_HOST: '##SUBDOMAIN##-crm.archops.fr'
    links:
      - mariadb
    volumes:
      - ./doli/documents:/var/www/documents

networks:
  default:
    external:
      name: knutech