version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name:  ##SUBDOMAIN##-mariadb
    networks:
      - knutech
    environment:
      MYSQL_ROOT_PASSWORD: '##DB_ROOT_PASSWORD##'
      MYSQL_DATABASE: ##DB_NAME##

  web:
    image: tuxgasy/dolibarr
    container_name: ##SUBDOMAIN##-dolibarr
    networks:
      - knutech
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: ##DB_USER##
      DOLI_DB_PASSWORD: '##DB_PASSWORD##'
      DOLI_DB_NAME: ##DB_NAME##
      DOLI_URL_ROOT: 'https://##SUBDOMAIN##.knutech.fr'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
      VIRTUAL_HOST: 'https://##SUBDOMAIN##.knutech.fr'
      VIRTUAL_PORT: 80
    links:
      - mariadb

networks:
  knutech:
