version: '3'
services:
  webapp:
    image: nginx:stable
    depends_on:
      - php
      - db
    networks:
      - knutech
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/default.d:/etc/nginx/default.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    ports:
      - "80:80"

  php:
    image: php:7.0-fpm
    restart: always
    networks:
      - knutech
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    networks:
      - knutech
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    env_file:
      - .env/db.env

networks:
  knutech:
